export const tableData = [
  {
    title: 'web3 Storage',
    solo: '64gb',
    whale: '64gb',
    team: '128gb',
    custom: '1TB',
  },
  {
    title: 'Upload Limit Size',
    solo: '25mb',
    whale: '25mb',
    team: '100mb',
    custom: '1Gb',
  },
  {
    title: 'Workspaces',
    solo: '2',
    whale: '2',
    team: '5',
    custom: '10',
  },
  {
    title: 'Members',
    solo: '3',
    whale: '3',
    team: '15',
    custom: '25',
  },
  {
    title: 'Members Management',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'Custom Domains',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'API Key',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'GeoID',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'Work-time Management',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'SmartContract Gateaway',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'Network Security',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'NFT Collection',
    solo: '5',
    whale: '5',
    team: '10',
    custom: '25',
  },
  {
    title: 'Create Token',
    solo: '0.8',
    whale: '0.8',
    team: '0.6',
    custom: '0.4',
  },
  {
    title: 'sell nft',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'Mint Access token',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'AI Generate Art',
    solo: '10',
    whale: '10',
    team: '50',
    custom: '100',
  },
  {
    title: 'Neyra AI Task, Ideas',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'Avatar',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: '2FA Auth',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'Pin-code',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'FaceID',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'Private Key',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'Voice ID',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: '',
  },
  {
    title: 'Multi-Sign',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: 'X',
  },
  {
    title: 'Ghost Doc',
    solo: '',
    whale: '',
    team: 'X',
    custom: '',
  },
  {
    title: 'Ghost Vault',
    solo: '',
    whale: '',
    team: 'X',
    custom: '',
  },
  {
    title: 'Ghost VPN',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: '',
  },
  {
    title: 'Neyra Profile',
    solo: 'X',
    whale: 'X',
    team: '',
    custom: '',
  },
  {
    title: 'NFT Notes',
    solo: '',
    whale: '',
    team: '',
    custom: '',
  },
  {
    title: 'Network Secuirty',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: 'X',
  },
  {
    title: 'CDN & Streaming',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: '',
  },
  {
    title: 'Neighborhood Cloud',
    solo: 'X',
    whale: 'X',
    team: 'X',
    custom: '',
  },
  {
    title: 'Storage',
    solo: '4gb',
    whale: '4gb',
    team: '128GB',
    custom: '1TB',
  },
];
